//
// Created by mbyrn on 04/06/2023.
//

#include <SFML/Graphics.hpp>

#define COUNTRY_UK 0
#define SUB_TYPE_UK_VANGUARD 0

#define COUNTRY_CHINA 1
#define SUB_TYPE_CHINA_092 11
#define SUB_TYPE_CHINA_094 12
#define SUB_TYPE_CHINA_096 13
#define SUB_TYPE_CHINA_095 14
#define SUB_TYPE_CHINA_093 15
#define SUB_TYPE_CHINA_091 16
#define SUB_TYPE_CHINA_YUAN 17
#define SUB_TYPE_CHINA_HAN 18
#define SUB_TYPE_CHINA_XIA 19

#define COUNTRY_IRAN 2
#define SUB_TYPE_IRAN_GHADIR 20
#define SUB_TYPE_IRAN_FETEH 21
#define SUB_TYPE_IRAN_NAHANG 22
#define SUB_TYPE_IRAN_GHAAEM 23
#define SUB_TYPE_IRAN_YUGO 24

#define COUNTRY_NKOREA 3
#define SUB_TYPE_NKOREA_WHISKY 30
#define SUB_TYPE_NKOREA_ROMEO 31
#define SUB_TYPE_NKOREA_SAMGO 32
#define SUB_TYPE_NKOREA_YUGO 33
#define SUB_TYPE_NKOREA_SINPO 34

#define SCREEN_REFESH_WAIT_MSECS 1000000



